# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [28]:
import numpy as np

In [29]:
def create_matrix(n):
  """
  In this function you should create matrix in order of n*n with random numbers 
  in the [n, n+100) interval.

  see the bellow link:
    https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

  Arguments:
    inputs:
      n: an integer describing the order of the matrix
    outputs:
      created matrix  
  """
  matrix = np.random.randint(n,n+100, size=(n, n))

  return matrix

In [11]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
n = int(input("please enter n: "))
matrix = create_matrix(n)
# print matrix
print(matrix)

[[ 62  98  41 106  55  64  90  91]
 [ 38  91  47  24  58  95  63  60]
 [ 57  77  83  13 100  45  17  55]
 [ 69  35   8  20  52  48  94  39]
 [ 23  35  82  86  90  67  77  78]
 [ 99  73  14 101  87  59  64  31]
 [107  48   9  73  15  82  54  40]
 [104  53  23  98  44  42  41  64]]


In [12]:
def count_digits(matrix):
  """
  In this function you should implement a routine to count the digits in the given matrix.

  Arguments:
    inputs:
      matrix: input matrix
    outputs:
      digits: a dictionary containing digits as its keys and the counted numbers as its value
  """

  digits = {}
  for i in range(10):
    digits[i] = 0
  flat = matrix.flatten()
  
  for num in flat:
    tmp = num 
    while(tmp > 0):
      index = tmp%10
      digits[index] += 1
      tmp = tmp // 10 
  return digits


In [13]:
"""
In this cell call the implemented function and print the result
"""

digits = count_digits(matrix)
print(digits)

{0: 11, 1: 15, 2: 9, 3: 13, 4: 18, 5: 15, 6: 10, 7: 13, 8: 13, 9: 14}


## Part B

In [26]:
def traverse_matrix(matrix):
  """
  Traverse the input matrix in the given manner then print result

  Arguments:
    inputs:
      matrix: input matrix
    outputs
  """

	#https://www.geeksforgeeks.org/print-matrix-in-zig-zag-fashion/ --helping link

  rows,columns= np.shape(matrix)
    
  solution=[[] for i in range(rows+columns-1)]
  
  for i in range(rows):
      for j in range(columns):
          sum=i+j
          if(sum%2 ==0):
  
              #add at beginning
              solution[sum].insert(0,matrix[i][j])
          else:
  
              #add at end of the list
              solution[sum].append(matrix[i][j])
          
              
  # print the solution as it as
  for i in solution:
      for j in i:
          print(j,end=" ")




In [30]:
traverse_matrix(matrix)
#print output

62 98 38 57 91 41 106 47 77 69 23 35 83 24 55 64 58 13 8 35 99 107 73 82 20 100 95 90 91 63 45 52 86 14 48 104 53 9 101 90 48 17 60 55 94 67 87 73 23 98 15 59 77 39 78 64 82 44 42 54 31 40 41 64 