# Q4

## Part A

In [1]:
import numpy as np

In [5]:
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""
matrix1 = [[1,2,3],
           [4,5,6],
           [7,8,9]]
matrix2 = [[1],
           [-1],
           [1]]
a = np.transpose(matrix1)
b = np.dot(a,matrix1)
b = np.linalg.inv(b)
b = np.dot(b,a)
b = np.dot(b,matrix2)
b = b+matrix1
print(b)



[[0.796875 1.796875 2.796875]
 [4.       5.       6.      ]
 [7.203125 8.203125 9.203125]]


## Part B

In [11]:
def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """
  res = np.zeros((3,3))
  temp = np.zeros((3,3))
  for column in range(3):
    for row in range(3):
      temp = B[row:row+3,column:column+3]
      con_res = np.sum(temp*A)
      res[row,column] = con_res

  return res

In [12]:
A = np.array([
    [1,1,1],
    [1,-9,1],
    [1,1,1]
])
B = np.array([
    [1,1,1,1,1],
    [1,2,2,2,1],
    [1,2,2,2,1],
    [1,2,2,2,1],
    [1,1,1,1,1]
])
print(window_sliding(A, B))

[[-7. -5. -7.]
 [-5. -2. -5.]
 [-7. -5. -7.]]
